version: "3.8"
services:
  mysql:
    image: "mysql:latest"
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql/data

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis:/var/lib/redis/data


volumes:
  mysql:
  redis:
