version: "3.8"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ./.env
    volumes:
        - postgres:/var/lib/postgresql/data

  redis:
    image: "clearlinux/redis:latest"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis:/var/lib/redis/data


volumes:
  postgres:
  redis:
